const fs = require('fs');
const path = require('path');

const root = process.cwd();
const htmlFiles = [];

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (entry.isFile() && full.toLowerCase().endsWith('.html')) htmlFiles.push(full);
  }
}

walk(root);

const rel = (p) => path.relative(root, p).replace(/\\/g, '/');

const titleMap = {
  'pages/blog.html': 'Blog | Synergy Engineering',
  'pages/blog-post.html': 'Blog Articles | Synergy Engineering',
  'pages/blog-post-detail.html': 'Blog Detail | Synergy Engineering',
  'pages/careers.html': 'Careers | Synergy Engineering',
  'pages/career-detail.html': 'Career Detail | Synergy Engineering',
  'pages/services.html': 'Services | Synergy Engineering'
};

const descMap = {
  'pages/index.html': 'Synergy Engineering delivers precision electrical testing, maintenance, and reliability solutions across India with authorized global partners.',
  'pages/about.html': 'Learn about Synergy Engineering, our mission, certifications, and expertise in electrical testing and industrial reliability.',
  'pages/products.html': 'Browse Synergy Engineering products from Megger, EMH, and Brother for testing, diagnostics, and industrial performance.',
  'pages/services.html': 'Explore Synergy Engineering service capabilities for calibration, diagnostics, preventive maintenance, and technical support.',
  'pages/industries.html': 'See how Synergy Engineering supports utilities, manufacturing, infrastructure, and critical industries with reliable testing solutions.',
  'pages/contact.html': 'Contact Synergy Engineering for product support, service requests, technical consultation, and business inquiries.',
  'pages/blog.html': 'Read the latest Synergy Engineering insights on electrical reliability, maintenance best practices, and industrial safety trends.',
  'pages/blog-post.html': 'Explore technical articles and practical engineering insights from Synergy Engineering experts.',
  'pages/blog-post-detail.html': 'Detailed engineering article from Synergy Engineering with practical guidance for industrial reliability and performance.',
  'pages/careers.html': 'Join Synergy Engineering and build your career in industrial technology, customer support, and engineering excellence.',
  'pages/career-detail.html': 'View role details, responsibilities, and application information for opportunities at Synergy Engineering.',
  'pages/quote.html': 'Request a fast and accurate quote from Synergy Engineering for products, services, and technical support requirements.',
  'pages/quote-print.html': 'Printable quote summary generated by Synergy Engineering for your product and service requirements.'
};

function titleCaseFromSlug(slug) {
  return slug
    .replace(/\.html$/i, '')
    .split('-')
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ');
}

function contactHref(fileRel) {
  if (fileRel.startsWith('pages/')) return 'contact.html';
  return '../pages/contact.html';
}

function productsHref(fileRel) {
  if (fileRel.startsWith('pages/')) return 'products.html';
  return '../pages/products.html';
}

function blogHref(fileRel) {
  if (fileRel.startsWith('pages/')) return 'blog.html';
  return '../pages/blog.html';
}

for (const file of htmlFiles) {
  const fileRel = rel(file);
  let c = fs.readFileSync(file, 'utf8');

  // Remove accidental replacement artifacts
  c = c.replace(/^\s*\$3\s*\r?\n?/gm, '');

  // Fix known broken link patterns
  c = c.replace(/href="\.\.\/pages\/bite5\.html"/g, 'href="../products/bite5.html"');
  c = c.replace(/href="\.\.\/pages\/(flir-t840|det24c)\.html"/g, `href="${productsHref(fileRel)}"`);

  if (fileRel.startsWith('blogs/')) {
    c = c.replace(/href="products\.html(\?brand=[^"]*)"/g, 'href="../pages/products.html$1"');
  }

  if (fileRel.startsWith('pages/')) {
    c = c.replace(/href="\.\.\/pages\/(.*?)"/g, 'href="$1"');
  }

  // Replace placeholder external PDF
  c = c.replace(/href="https:\/\/example\.com\/catalogue\.pdf"/g, `href="${contactHref(fileRel)}"`);

  // Replace social placeholder links with real destinations
  c = c.replace(/<a\s+href="#"\s+target="_blank"([^>]*)>\s*social_leaderboard\s*<\/a>/gi,
    '<a href="https://linkedin.com/company/synergy-engineering" target="_blank" rel="noopener noreferrer"$1>social_leaderboard</a>');
  c = c.replace(/<a\s+href="#"\s+target="_blank"([^>]*)>\s*language\s*<\/a>/gi,
    '<a href="https://synergy-engg.com" target="_blank" rel="noopener noreferrer"$1>language</a>');

  // Fix downloadable '#' links to contact page for request flow
  c = c.replace(/href="#"\s+onclick="alert\('Downloading[^']*'\)"/g, `href="${contactHref(fileRel)}"`);

  // Convert tag chips in blog detail from # to blog page
  if (fileRel === 'pages/blog-post-detail.html') {
    c = c.replace(/href="#"/g, (m, offset) => {
      const before = c.slice(Math.max(0, offset - 120), offset + 200);
      if (/uppercase rounded/.test(before)) return `href="${blogHref(fileRel)}"`;
      return m;
    });
  }

  // Fix chat CTA placeholders
  c = c.replace(/href="#"(\s+title="Chat with an Engineer")/g, 'href="https://wa.me/912225805555"$1');

  // Normalize WhatsApp numbers
  c = c.replace(/https:\/\/wa\.me\/(918023456789|15551234567|1800SYNERGY)/g, 'https://wa.me/912225805555');

  // Any remaining target blank '#' becomes contact page
  c = c.replace(/href="#"(\s+target="_blank")/g, `href="${contactHref(fileRel)}"$1`);

  // Add rel security for all target blank links
  c = c.replace(/<a\b([^>]*?)target="_blank"([^>]*)>/gi, (full, pre, post) => {
    if (/\brel\s*=\s*"[^"]*"/i.test(full)) {
      return full.replace(/rel\s*=\s*"([^"]*)"/i, (_, v) => {
        const tokens = new Set(v.split(/\s+/).filter(Boolean));
        tokens.add('noopener');
        tokens.add('noreferrer');
        return `rel="${Array.from(tokens).join(' ')}"`;
      });
    }
    return `<a${pre}target="_blank" rel="noopener noreferrer"${post}>`;
  });

  // Ensure img alt exists (use data-alt when present)
  c = c.replace(/<img\b([^>]*?)>/gi, (full, attrs) => {
    if (/\balt\s*=\s*"[^"]*"/i.test(full)) return full;
    const dataAltMatch = full.match(/\bdata-alt\s*=\s*"([^"]*)"/i);
    const altText = dataAltMatch?.[1]?.trim() || 'Synergy Engineering image';
    return `<img alt="${altText.replace(/"/g, '&quot;')}"${attrs}>`;
  });

  // Ensure title exists
  if (!/<title>[^<]+<\/title>/i.test(c)) {
    const base = path.basename(fileRel);
    let title = titleMap[fileRel];
    if (!title) {
      if (fileRel.startsWith('blogs/')) title = `${titleCaseFromSlug(base)} | Synergy Engineering Blog`;
      else if (fileRel.startsWith('products/')) title = `${titleCaseFromSlug(base)} | Synergy Engineering`;
      else title = `${titleCaseFromSlug(base)} | Synergy Engineering`;
    }
    c = c.replace(/<head>/i, `<head>\n    <title>${title}</title>`);
  }

  // Ensure meta description exists
  const hasDesc = /<meta\b[^>]*\bname\s*=\s*['"]description['"][^>]*\bcontent\s*=\s*['"][^'"]+['"][^>]*>/i.test(c)
    || /<meta\b[^>]*\bcontent\s*=\s*['"][^'"]+['"][^>]*\bname\s*=\s*['"]description['"][^>]*>/i.test(c);

  if (!hasDesc) {
    const base = path.basename(fileRel);
    const generated = descMap[fileRel]
      || (fileRel.startsWith('blogs/')
        ? `Read ${titleCaseFromSlug(base)} and other expert insights from Synergy Engineering on industrial reliability and electrical performance.`
        : fileRel.startsWith('products/')
          ? `Explore ${titleCaseFromSlug(base)} product information, applications, and support from Synergy Engineering.`
          : `Discover ${titleCaseFromSlug(base)} information from Synergy Engineering.`);

    c = c.replace(/<meta\s+charset="utf-8"\s*\/?\s*>/i, (m) => `${m}\n    <meta name="description" content="${generated.replace(/"/g, '&quot;')}"/>`);
    if (!/<meta\s+charset=/i.test(c)) {
      c = c.replace(/<head>/i, `<head>\n    <meta name="description" content="${generated.replace(/"/g, '&quot;')}"/>`);
    }
  }

  fs.writeFileSync(file, c, 'utf8');
}

console.log(`Updated ${htmlFiles.length} HTML files.`);
